terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
grabABI argc: 4 [1:0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359] [2:--known] [3:-e] 
grabABI 0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359 --known -e 
